spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/skcoins?useUnicode=true&characterEncoding=utf8
    username: root
    password: 111111
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true

  logging:
    config: classpath:logback.xml
    
  mvc:
    view:
      # 页面默认前缀目录
      prefix: /WEB-INF/jsp/
      # 响应页面默认后缀
      suffix: .jsp  

mybatis:
  type-aliases-package: com.softisland.model
  mapper-locations: classpath:com/softisland/mapper/*.xml
mapper:
  mappers:
    - com.softisland.common.MyBaseMapper
  not-empty: false
  identity: MYSQL      
      
server:
  port: 80
  
contract:
  eth-address:  
  token-address: !!str 0x4e2E80dA333760Bcb9BEB1DD9f1c216Ac51A5D73
  eth-send-ower-prikey: 
  token-send-ower-prikey: !!str e72e616234938238d1275aa6b4554d218dbf9cc44c92754e8bcc7deb1496e7e2
  bankroll: 
    masterPrikey: !!str e72e616234938238d1275aa6b4554d218dbf9cc44c92754e8bcc7deb1496e7e2
    contractAddress: !!str 0x4e2E80dA333760Bcb9BEB1DD9f1c216Ac51A5D73
    adminPrikey: 
  